apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-api-asp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client-api-asp
  template:
    metadata:
      labels:
        app: client-api-asp
    spec:
      containers:
      - name: client-api-asp
        image: kdeit/wtm-client-asp:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: app-config
          - secretRef:
              name: app-config