namespace OtusKdeBus.Model;

public enum MessageType
{
    USER_CREATED = 0,
    INCIDENT_CREATED = 1,
    SF_SYNC_SUCCESS,
    SF_SYNC_ERROR,
    PHARMACY_SUPPORT_CHECK_SUCCESS,
    PHARMACY_SUPPORT_CHECK_ERROR
}