apiVersion: batch/v1
kind: Job
metadata:
  name: client-seed
spec:
  template:
    spec:
      containers:
      - name: seeder
        image: kdeit/wtm-client-seeder-asp:latest
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: app-config
          - secretRef:
              name: app-config
      restartPolicy: Never
  backoffLimit: 4